version: '3.4'

networks:
  db:
  app:
  acc:
volumes:
  db:
  nginx:
services:
  ems:
    container_name: ems
    image: ${DOCKER_REGISTRY-}ems
    build:
      context: .
      dockerfile: Ems/Dockerfile
    networks:
      - db
      - app
      - acc
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - db
  nginx:
    container_name: nginx
    image: nginx:1.25
    restart: always
    volumes:
      - nginx:/etc/nginx/templates
    ports:
      - ${MAIN_PORT}:80
    networks:
      - app
      - acc
    environment:
      - NGINX_HOST=ems
      - NGINX_PORT=80
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.3
    restart: always
    command: "${KEYCLOAK_START_COMMAND}"
    ports:
      - 5000:8080
    networks:
      - app
      - acc
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD